import type { Metadata } from 'next';
import { Pixelify_Sans } from 'next/font/google';

import { ThemeProvider } from '@/components/Theme-Provider';
import { cn } from '@/lib/utils';

import './globals.css';

const fontFamily = Pixelify_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Wordle clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
